# Generated by Django 6.0.5 on 2026-05-18 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bengkel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_bengkel', models.CharField(max_length=200, verbose_name='Nama Bengkel')),
                ('pemilik', models.CharField(max_length=150, verbose_name='Pemilik')),
                ('alamat', models.TextField(verbose_name='Alamat')),
                ('kota', models.CharField(max_length=100, verbose_name='Kota')),
                ('no_telp', models.CharField(max_length=20, verbose_name='No. Telepon')),
                ('jenis_kendaraan', models.CharField(help_text='Pisahkan dengan koma, cth: Mobil, Motor', max_length=200, verbose_name='Jenis Kendaraan Ditangani')),
                ('keterangan', models.TextField(blank=True, default='', verbose_name='Keterangan')),
                ('tanggal_input', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Input')),
            ],
            options={
                'verbose_name': 'Bengkel',
                'verbose_name_plural': 'Data Bengkel',
                'ordering': ['nama_bengkel'],
            },
        ),
        migrations.CreateModel(
            name='JasaServis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=50, unique=True, verbose_name='Kode')),
                ('nama_jasa', models.CharField(max_length=200, verbose_name='Nama Jasa')),
                ('biaya', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Biaya')),
                ('keterangan', models.TextField(blank=True, default='', verbose_name='Keterangan')),
                ('tanggal_input', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Input')),
            ],
            options={
                'verbose_name': 'Jasa Servis',
                'verbose_name_plural': 'Data Jasa Servis',
                'ordering': ['kode'],
            },
        ),
        migrations.CreateModel(
            name='Kendaraan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('mobil', 'Mobil'), ('motor', 'Motor'), ('sepeda_listrik', 'Sepeda Listrik')], max_length=20, verbose_name='Jenis Kendaraan')),
                ('nomor_polisi', models.CharField(max_length=20, unique=True, verbose_name='Nomor Polisi')),
                ('merk', models.CharField(max_length=100, verbose_name='Merk')),
                ('tipe', models.CharField(max_length=100, verbose_name='Tipe/Model')),
                ('tahun_pembuatan', models.PositiveIntegerField(verbose_name='Tahun Pembuatan')),
                ('warna', models.CharField(max_length=50, verbose_name='Warna')),
                ('no_rangka', models.CharField(blank=True, default='', max_length=100, verbose_name='Nomor Rangka')),
                ('no_mesin', models.CharField(blank=True, default='', max_length=100, verbose_name='Nomor Mesin')),
                ('pemilik_pengguna', models.CharField(max_length=150, verbose_name='Pemilik/Pengguna')),
                ('keterangan', models.TextField(blank=True, default='', verbose_name='Keterangan')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('tanggal_input', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Input')),
            ],
            options={
                'verbose_name': 'Kendaraan',
                'verbose_name_plural': 'Data Kendaraan',
                'ordering': ['nomor_polisi'],
            },
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=50, unique=True, verbose_name='Kode')),
                ('nama_sparepart', models.CharField(max_length=200, verbose_name='Nama Spare Part')),
                ('harga', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Harga Satuan')),
                ('keterangan', models.TextField(blank=True, default='', verbose_name='Keterangan')),
                ('tanggal_input', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Input')),
            ],
            options={
                'verbose_name': 'Spare Part',
                'verbose_name_plural': 'Data Spare Part',
                'ordering': ['kode'],
            },
        ),
        migrations.CreateModel(
            name='Pemeliharaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_servis', models.CharField(max_length=50, unique=True, verbose_name='No. Servis')),
                ('tanggal_servis', models.DateField(verbose_name='Tanggal Servis')),
                ('km_saat_servis', models.PositiveIntegerField(blank=True, null=True, verbose_name='KM Saat Servis')),
                ('keterangan', models.TextField(blank=True, default='', verbose_name='Keterangan')),
                ('total_biaya_sparepart', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Biaya Spare Part')),
                ('total_biaya_jasa', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Biaya Jasa')),
                ('total_biaya', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Biaya')),
                ('tanggal_input', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Input')),
                ('tanggal_update', models.DateTimeField(auto_now=True, verbose_name='Tanggal Update')),
                ('bengkel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pemeliharaan.bengkel', verbose_name='Bengkel')),
                ('kendaraan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pemeliharaan.kendaraan', verbose_name='Kendaraan')),
            ],
            options={
                'verbose_name': 'Pemeliharaan',
                'verbose_name_plural': 'Data Pemeliharaan',
                'ordering': ['-tanggal_servis', '-no_servis'],
            },
        ),
        migrations.CreateModel(
            name='DetailJasaServis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biaya', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Biaya')),
                ('jasa_servis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pemeliharaan.jasaservis', verbose_name='Jasa Servis')),
                ('pemeliharaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_jasaservis', to='pemeliharaan.pemeliharaan', verbose_name='Pemeliharaan')),
            ],
            options={
                'verbose_name': 'Detail Jasa Servis',
                'verbose_name_plural': 'Detail Jasa Servis',
            },
        ),
        migrations.CreateModel(
            name='DetailSparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField(default=1, verbose_name='Jumlah')),
                ('harga_satuan', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Harga Satuan')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Subtotal')),
                ('pemeliharaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_sparepart', to='pemeliharaan.pemeliharaan', verbose_name='Pemeliharaan')),
                ('sparepart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pemeliharaan.sparepart', verbose_name='Spare Part')),
            ],
            options={
                'verbose_name': 'Detail Spare Part',
                'verbose_name_plural': 'Detail Spare Part',
            },
        ),
    ]
