# Generated by Django 6.0.5 on 2026-05-18 04:50

import pemeliharaan.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemeliharaan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kendaraan',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=pemeliharaan.models.kendaraan_foto_path, verbose_name='Foto Kendaraan'),
        ),
    ]
