# Generated by Django 6.0.5 on 2026-05-18 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemeliharaan', '0002_kendaraan_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='KonsumsiBensin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(verbose_name='Tanggal Pengisian')),
                ('km_pengisian', models.PositiveIntegerField(blank=True, null=True, verbose_name='KM Saat Pengisian')),
                ('liter', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Jumlah Liter')),
                ('harga_per_liter', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Harga per Liter')),
                ('total_biaya', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Biaya')),
                ('spbu', models.CharField(blank=True, default='', max_length=200, verbose_name='Nama SPBU')),
                ('keterangan', models.TextField(blank=True, default='', verbose_name='Keterangan')),
                ('tanggal_input', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Input')),
                ('kendaraan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pemeliharaan.kendaraan', verbose_name='Kendaraan')),
            ],
            options={
                'verbose_name': 'Konsumsi Bensin',
                'verbose_name_plural': 'Data Konsumsi Bensin',
                'ordering': ['-tanggal'],
            },
        ),
    ]
